"""djangorestframework-services — service/selector layer for Django REST Framework.

Public API re-exports live here. Importing the top-level package is enough
for typical usage; deeper imports (``rest_framework_services.mutations``,
``rest_framework_services.exceptions``, ``rest_framework_services.types``,
``rest_framework_services.views``, ``rest_framework_services.viewsets``,
``rest_framework_services.selectors``) are stable and supported.
"""

from rest_framework_services.dispatch import (
    adispatch_spec,
    arender_spec_output,
    base_pool,
    base_serializer_context,
    build_offline_context,
    combine_progress,
    dispatch_spec,
    enforce_permissions,
    null_progress,
    render_spec_output,
    unguarded_specs,
)
from rest_framework_services.exceptions import (
    AdditionalInputRequired,
    ServiceError,
    ServiceValidationError,
)
from rest_framework_services.implements import implements
from rest_framework_services.is_async import is_async
from rest_framework_services.jsonschema import (
    filterset_to_json_schema,
    output_to_json_schema,
    serializer_to_json_schema,
    spec_to_json_schema,
)
from rest_framework_services.mutations import (
    acreate_from_input,
    apply_input,
    aupdate_from_input,
    create_from_input,
    update_from_input,
)
from rest_framework_services.registry import SpecRegistry
from rest_framework_services.selectors import (
    AsyncSelector,
    ListSelector,
    RetrieveSelector,
    Selector,
    acall_selector,
    apply_queryset_shaping,
    arun_selector,
    call_selector,
    is_queryset,
    run_selector,
)
from rest_framework_services.services import (
    CreateService,
    DeleteService,
    UpdateService,
    acall_service,
    acreate_model,
    adelete_collection,
    adelete_model,
    arun_service,
    aupdate_model,
    call_service,
    create_model,
    delete_collection,
    delete_model,
    run_service,
    update_model,
)
from rest_framework_services.types import (
    DEFAULT_JSON_SCHEMA_REGISTRY,
    UNSET,
    ArgumentBinding,
    ChangeResult,
    ChildCollectionChange,
    ChildSpec,
    DispatchResult,
    FieldChange,
    HttpExtras,
    InputRequired,
    InputRequiredType,
    JsonSchemaRegistry,
    NoInput,
    NotClientInput,
    NotClientInputType,
    OfflineContext,
    OfflineHttpRequest,
    OfflineServiceView,
    PolymorphicServiceSpec,
    ProgressReporter,
    QueryParam,
    RegisteredSpec,
    SelectorKind,
    SelectorSpec,
    ServiceSpec,
    ServiceView,
    TargetGuard,
    UnknownArguments,
    UnsetType,
    UrlKwarg,
    ViewHooks,
    validate_channel_names,
)
from rest_framework_services.version import __version__
from rest_framework_services.views import (
    SelectorListView,
    SelectorRetrieveView,
    ServiceCreateView,
    ServiceDeleteView,
    ServiceUpdateView,
)
from rest_framework_services.views.mutation.mutation_flow_mixin import MutationFlowMixin
from rest_framework_services.views.mutation.utils import (
    build_input_serializer,
    build_input_serializer_from_data,
    resolve_mutation_instance,
    validate_input,
)
from rest_framework_services.views.utils import resolve_callable_kwargs
from rest_framework_services.viewsets import (
    ActionSerializerResolver,
    SelectorListMixin,
    SelectorRetrieveMixin,
    SelectorViewSet,
    ServiceCreateMixin,
    ServiceDestroyMixin,
    ServiceUpdateMixin,
    ServiceViewSet,
    selector_action,
    service_action,
)

__all__ = [
    "ActionSerializerResolver",
    "ArgumentBinding",
    "AsyncSelector",
    "ChangeResult",
    "ChildCollectionChange",
    "ChildSpec",
    "CreateService",
    "DEFAULT_JSON_SCHEMA_REGISTRY",
    "DeleteService",
    "DispatchResult",
    "FieldChange",
    "HttpExtras",
    "InputRequired",
    "InputRequiredType",
    "JsonSchemaRegistry",
    "ListSelector",
    "MutationFlowMixin",
    "NoInput",
    "NotClientInput",
    "NotClientInputType",
    "OfflineContext",
    "OfflineHttpRequest",
    "OfflineServiceView",
    "PolymorphicServiceSpec",
    "ProgressReporter",
    "QueryParam",
    "RegisteredSpec",
    "RetrieveSelector",
    "Selector",
    "SelectorKind",
    "SelectorListMixin",
    "SelectorListView",
    "SelectorRetrieveMixin",
    "SelectorRetrieveView",
    "SelectorSpec",
    "SelectorViewSet",
    "ServiceCreateMixin",
    "ServiceCreateView",
    "ServiceDeleteView",
    "ServiceDestroyMixin",
    "AdditionalInputRequired",
    "ServiceError",
    "ServiceSpec",
    "ServiceUpdateMixin",
    "ServiceUpdateView",
    "ServiceValidationError",
    "ServiceView",
    "ServiceViewSet",
    "SpecRegistry",
    "TargetGuard",
    "UNSET",
    "UnknownArguments",
    "ViewHooks",
    "UnsetType",
    "UrlKwarg",
    "UpdateService",
    "acall_selector",
    "acall_service",
    "acreate_from_input",
    "acreate_model",
    "adelete_collection",
    "adelete_model",
    "adispatch_spec",
    "apply_input",
    "apply_queryset_shaping",
    "arender_spec_output",
    "arun_selector",
    "arun_service",
    "aupdate_from_input",
    "aupdate_model",
    "base_pool",
    "base_serializer_context",
    "null_progress",
    "build_input_serializer",
    "build_input_serializer_from_data",
    "build_offline_context",
    "call_selector",
    "call_service",
    "combine_progress",
    "create_from_input",
    "create_model",
    "delete_collection",
    "delete_model",
    "dispatch_spec",
    "enforce_permissions",
    "filterset_to_json_schema",
    "implements",
    "is_async",
    "is_queryset",
    "output_to_json_schema",
    "render_spec_output",
    "resolve_callable_kwargs",
    "resolve_mutation_instance",
    "run_selector",
    "run_service",
    "selector_action",
    "serializer_to_json_schema",
    "service_action",
    "spec_to_json_schema",
    "unguarded_specs",
    "update_from_input",
    "update_model",
    "validate_input",
    "validate_channel_names",
]
